apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: traffic
  namespace: squidgame
spec:
  service:  svc-grpc-kafka
  backends:
  - service: svc-grpc-kafka
    weight: 400m
  - service: svc-grpc-rabbit
    weight: 300m
  - service: error-injector
    weight: 300m