version: '3'

services:

  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   container_name: zookeeper
  #   ports:
  #   - "2181:2181"
  #   restart: always
  #   networks:
  #   - sop1-net

  # kafka:
  #   image: wurstmeister/kafka
  #   container_name: kafka
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: kafka
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_CONNECT_BOOTSTRAP_SERVERS: localhost:9092
  #   ports:
  #   - "9092:9092"
  #   restart: always
  #   volumes:
  #   - ./apache-kafka-volume:/tmp/kafka-logs
  #   depends_on:
  #   - zookeeper
  #   networks:
  #   - sop1-net

  gRPC-Server-producer: 
    image : villa01/grpc_server   
    container_name: grpc_go_server 
    ports:
    - "50051:50051"
    restart: always
    depends_on:
    - kafka
    networks:
    - sop1-net

#   gRPC-Server-consumer: 
#     image : consumer   
#     container_name: go_consumer 
#     depends_on:
#     - kafka
#     networks:
#     - sop1-net

networks:
  sop1-net:
    driver: bridge